language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer

jdk:
  - oraclejdk8

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_failure:
  - find . -name idnadrev.log -exec tail -n 500 {} \;