= Idnadrev documentation
:Author:    Christian Löhnert
:Email:     krampenschiesser@gmail.com


== About

Idnadrev is a task management and knowledge application
that helps to organize your ideas, projects and any kind of information.
It is also a test project for an activity based JavaFX dialog framework. +
I'm getting close to the first release which will be the version 0.5. +
I recently created a little tour to give you a more detailed impression on idnadrev. +
link:doc/src/asciidoc/tour.adoc[*Take a look at the tour*]

== Building

Building idnadrev is based on http://www.gradle.org/[gradle].
If you don't have gradle installed, no worries.
Use the provided gradle wrapper *gradlew*
[source,shell]
----
$ ./gradlew help
$ ./gradlew build
----

=== Check-in build

Currently disabled because travis doesn't have the JDK8_u20 yet (and controlsfx depends on it).

image:https://travis-ci.org/krampenschiesser/idnadrev.svg?branch=master["Build Status", link="https://travis-ci.org/krampenschiesser/idnadrev"]

== Parameters useful for testing

In order to not see the javaFX dialogs while running your test from the IDE you should use:
[source]
-Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw

=== Xvfb
Sadly monocle was removed again from the JDK ea build 1.8.20 and I know need an xvfb:

[source,shell]
$ mkdir /tmp/xvfb_test
$ Xvfb :99 -fbdir /tmp/xvfb_test -ac -extension GLX

== License

Idnadrev is licensed under the http://apache.org/licenses/LICENSE-2.0[Apache 2.0 license].